name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0

      - name: Install node.js v16
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # tag=v3.1.0
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn --immutable

      - name: Test
        run: yarn test --coverage --passWithNoTests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b # tag=v2.1.0
        with:
          file: ./coverage/coverage-final.json
